#!/bin/bash
set -e


# Install Zero Tier
echo "DEBUG: Installing ZeroTier..."
curl -s https://install.zerotier.com/ | sudo bash


sudo sed -i '/^exit 0/d' /etc/rc.local

sudo tee -a "/etc/rc.local" > /dev/null <<EOT
# ZeroTier Start
if [ -e /boot/zt ]; then
    zt_regenerate=\$(sed '2q;d' /boot/zt)
    zt_network=\$(sed '1q;d' /boot/zt)

    if [ \$zt_regenerate = "true" ]; then
        if pgrep -x "zerotier-one" > /dev/null; then
            systemctl stop zerotier-one
        fi
        rm -rf /var/lib/zerotier-one/identity.secret
        rm -rf /var/lib/zerotier-one/identity.public
        if ! pgrep -x "zerotier-one" > /dev/null; then
            systemctl start zerotier-one
        fi
    fi

    if [ -n "\$zt_network" ]; then
        mkdir -p "/var/lib/zerotier-one/networks.d"
        touch "/var/lib/zerotier-one/networks.d/\${zt_network}.conf"
    fi

   rm /boot/zt
fi
# ZeroTier End

exit 0
EOT

. $path_to_helper/write "components" "zerotier" "installed" "true"