#!/bin/bash
set -e


# Install Zero Tier
echo "DEBUG: Installing ZeroTier..."
curl -s https://install.zerotier.com/ | sudo bash


sudo sed -i '/^exit 0/d' /etc/rc.local

sudo tee -a "/etc/rc.local" > /dev/null <<EOT
# ZeroTier Start
if [ -e /boot/zt ]; then
    zt_regenerate=\$(sed '2q;d' /boot/zt)
    zt_network=\$(sed '1q;d' /boot/zt)

    if [[ \$zt_regenerate = "true" ]]; then
        echo "it worked" | sudo tee -a /home/pi/zero
        sudo zerotier-idtool generate identity.secret identity.public
    else
        echo "Skipping Identity Regeneration"
    fi

    if [ -z \$zt_network ]; then
        echo "No Network Provided"
    else
        mkdir -p "/var/lib/zerotier-one/networks.d"
        touch "/var/lib/zerotier-one/networks.d/\${zt_network}.conf"
    fi

    rm /boot/zt


#    if [ -e /usr/bin/slack ]; then
#        info=\$(zerotier-cli info)
#        sudo -u root slack "Computer \${info} sent a request to join the network \${zt_network}."
#    fi
fi
# ZeroTier End

exit 0
EOT

. $path_to_helper/write "components" "zerotier" "installed" "true"