#!/bin/bash
set -e

config_path=$(jq -r '.[] | select( .name == "update" ) | .config_path' /etc/auxcli/commands.json)

config="/etc/auxcli/config.json"
tmp="/etc/auxcli/config.json.tmp"

args_short=($(jq -r '.[].arg_short' $config_path))
args_long=($(jq -r '.[].arg_long' $config_path))
auxcli debug-printf "DEBUG (update): Config path: %s\n" "$config_update"
args=("${args_short[@]}" "${args_long[@]}")

update_aux=false
automatic_update_aux=false
update_cli=false
automatic_update_cli=false
update_pi=false
automatic_update_pi=false

# readarray splits each newline into one element in the array
readarray -t args_desc < <(jq '.[].short_desc' $config_path)

usage() {
    printf "\nUsage:    auxcli update [OPTIONS]\n\n"
    printf "Update auxcli, casualOS, or the RaspberryPi.\n\n"
    printf "OPTIONS:\n"
    for ((i = 0; i < ${#args[@]}; i++)); do
        printf "\t%-2s\t%-10s\t%s\n" "${args_short[$i]}" "${args_long[$i]}" "${args_desc[$i]}"
    done
    exit 1
}

err_check() {
    # First error check
    # Show the usage menu if there aren't any arguments
    auxcli debug-printf "DEBUG (update): First error check.\n"
    if [ $# -eq 0 ]; then
        printf "\nYou need to pass an argument.\n"
        usage
    fi

    # Second error check
    # Throw an error messege if the first argument isn't valid
    auxcli debug-printf "DEBUG (update): Second error check.\n"
    if [[ ! ${args[*]} =~ $1 ]]; then
        printf "\n\"%s\" is an invalid argument.\n" "$1"
        printf "Run auxcli update -h for help.\n\n"
        exit 1
    fi
}

err_check "$@"

while [[ $# -gt 0 ]]; do
    case "$1" in

    -a | --aux)
        auxcli debug-printf "DEBUG (update): Setting 'update_aux' to 'true'.\n"
        update_aux=true
        shift # past argument
        ;;
    -A | --aux-auto)
        auxcli debug-printf "DEBUG (update): Setting 'automatic_update_aux' to 'true'.\n"
        automatic_update_aux=true
        shift # past argument
        ;;
    -c | --cli)
        auxcli debug-printf "DEBUG (update): Setting 'update_cli' to 'true'.\n"
        update_cli=true
        shift # past argument
        ;;
    -C | --cli-auto)
        auxcli debug-printf "DEBUG (update): Setting 'automatic_update_cli' to 'true'.\n"
        automatic_update_cli=true
        shift # past argument
        ;;
    -p | --pi)
        auxcli debug-printf "DEBUG (update): Setting 'update_pi' to 'true'.\n"
        update_pi=true
        shift # past argument
        ;;
    -P | --pi-auto)
        auxcli debug-printf "DEBUG (update): Setting 'automatic_update_pi' to 'true'.\n"
        automatic_update_pi=true
        shift # past argument
        ;;
    -y)
        auxcli debug-printf "DEBUG (update): Setting 'agree' to 'true'.\n"
        agree=true
        shift # past argument
        ;;
    -h | -help | --help)
        usage
        shift # past argument
        ;;
    esac
done

vercomp () {
    if [[ $1 == $2 ]]; then
        auxcli debug-printf "DEBUG (update): Version numbers are the same.\n"
        return 1
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++)); do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++)); do
        if [[ -z ${ver2[i]} ]]; then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]})); then
            auxcli debug-printf "DEBUG (update): New Version number is higher.\n"
            return 0
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]})); then
            auxcli debug-printf "DEBUG (update): New Version number is lower.\n"
            return 1
        fi
    done
    return 0
}

version_check() {
    printf "Checking for newer versions of AUXCLI...\n"
    auxcli debug-printf "DEBUG (update): CURL the latest config.json\n"
    curl https://raw.githubusercontent.com/casual-simulation/aux-cli/2.0.0/etc/auxcli/config.json --output /home/pi/config.json

    new_version=$(jq -r '.version' /home/pi/config.json) 
    old_version=$(jq -r '.version' $config)
    auxcli debug-printf "DEBUG (update): New Version: %s\n" "$new_version"
    auxcli debug-printf "DEBUG (update): Old Version: %s\n" "$old_version"
    sudo rm -rf /home/pi/config.json

    auxcli debug-printf "DEBUG (update): Compare version numbers.\n"
    if vercomp $new_version $old_version; then
        printf "There is a newer version of AUXCLI available.\n"
        if $agree; then
            auxcli debug-printf "DEBUG (update): Auto-agree was set.\n"
            return 0
        else
            read -p "There is a newer version of AUXCLI available. Press 'y' to update now, or press anything else to exit." -n 1 -r
            echo # Gives us a newline
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                auxcli debug-printf "DEBUG (update): Agreed.\n"
                return 0
            else
                auxcli debug-printf "DEBUG (update): Disagreed.\n"
                return 1
            fi
        fi
    else
        printf "You have the latest version of AUXCLI.\n"
        return 1
    fi
}

update_aux() {
    auxcli debug-printf "DEBUG (update): Running 'update_aux'.\n"
    auxcli debug-printf "DEBUG (update): CURL the latest docker-compose.arm32.yml.\n"
    sudo curl https://raw.githubusercontent.com/casual-simulation/aux/master/docker/docker-compose.arm32.yml --output /home/pi/docker-compose.yml
    docker-compose -f /home/pi/docker-compose.yml pull && docker-compose -f /home/pi/docker-compose.yml up -d
}

automatic_update_aux() {
    if ! jq -r '.autoupdate_aux' $config 1> /dev/null; then
    auxcli debug-printf "DEBUG (update): Running 'automatic_update_aux'.\n"
        printf "Enabling Automatic updates for AUX.\n"
        (
            crontab -l
            echo "@daily auxcli update -a"
        ) | crontab -
        auxcli write "config" "autoupdate_aux" "true"
    else
        printf "Disabling Automatic updates for AUX.\n"
        crontab -l | grep -v "auxcli update -a" | crontab -
        auxcli write "config" "autoupdate_aux" "false"
    fi
}

update_cli() {
    auxcli debug-printf "DEBUG (update): Running 'update_cli'.\n"
    if version_check; then
        auxcli debug-printf "DEBUG (update): CURL the latest config.json\n"
        curl https://raw.githubusercontent.com/casual-simulation/aux-cli/2.0.0/install.sh --output install.sh && sudo bash install.sh
        sudo rm -rf install.sh
    fi
}

automatic_update_cli() {
    if ! jq -r '.autoupdate_cli' $config 1> /dev/null; then
    auxcli debug-printf "DEBUG (update): Running 'automatic_update_cli'.\n"
        printf "Enabling Automatic updates for AUXCLI.\n"
        (
            crontab -l
            echo "@hourly auxcli update -c -y"
        ) | crontab -
        auxcli write "config" "autoupdate_cli" "true"
    else
        printf "Disabling Automatic updates for AUXCLI.\n"
        crontab -l | grep -v "auxcli update -c -y" | crontab -
        auxcli write "config" "autoupdate_cli" "false"
    fi
}

update_pi() {
    auxcli debug-printf "DEBUG (update): Running 'update_pi'.\n"
    sudo apt-get update && sudo apt-get upgrade -y
}

automatic_update_pi() {
    if ! jq -r '.autoupdate_pi' $config 1> /dev/null; then
    auxcli debug-printf "DEBUG (update): Running 'automatic_update_pi'.\n"
        printf "Enabling Automatic updates for your RaspberryPi (apt-get).\n"
        (
            crontab -l
            echo "@daily auxcli update -p"
        ) | crontab -
        auxcli write "config" "autoupdate_pi" "true"
    else
        printf "Disabling Automatic updates for your RaspberryPi (apt-get).\n"
        crontab -l | grep -v "auxcli update -p" | crontab -
        auxcli write "config" "autoupdate_pi" "false"
    fi

}

run_steps() {
    auxcli debug-printf "DEBUG (update): DHCPCD set check.\n"
    if auxcli available dhcpcd; then auxcli dhcpcd -s; fi

    if $update_aux; then update_aux; fi
    if $automatic_update_aux; then automatic_update_aux; fi
    if $update_cli; then update_cli; fi
    if $automatic_update_cli; then automatic_update_cli; fi
    if $update_pi; then update_pi; fi
    if $automatic_update_pi; then automatic_update_pi; fi

    auxcli debug-printf "DEBUG (update): DHCPCD unset check.\n"
    if auxcli available dhcpcd; then auxcli dhcpcd -u; fi
}

run_steps
