#!/bin/bash
set -e

sudo apt-get remove -y usbmount

# Modify the /lib/systemd/system/systemd-udevd.service
echo "Modifying /lib/systemd/system/systemd-udevd.service"
sudo sed -i "s/^PrivateMounts=no/PrivateMounts=yes/g" /lib/systemd/system/systemd-udevd.service

auxcli write "components" "usbmount" "installed" "false"