#!/bin/bash
set -e

install_path=$(jq -r '.[] | select( .name == "pishrink" ) | .install_path' /etc/auxcli/components.json)

echo "Installing PiShrink."
sudo chmod +x $install_path/pishrink.sh
sudo mv -f $install_path/pishrink.sh /usr/local/bin

auxcli write "components" "pishrink" "installed" "true"