#!/bin/bash
set -e

. $path_to_helper/debug-printf "DEBUG (pishrink-install): Installing Pishrink.\n"

install_path=$(jq -r '.[] | select( .name == "pishrink" ) | .install_path' /etc/auxcli/components.json)
. $path_to_helper/debug-printf "DEBUG (pishrink-install): install_path: %s\n" "$install_path"

. $path_to_helper/debug-printf "DEBUG (pishrink-install): Making pishrink executable.\n"
sudo chmod +x $install_path/pishrink.sh

. $path_to_helper/debug-printf "DEBUG (pishrink-install): Copying pishrink to /usr/local/bin\n"
sudo mv -f $install_path/pishrink.sh /usr/local/bin

. $path_to_helper/write "components" "pishrink" "installed" "true"