#!/bin/bash
set -e

config="/etc/auxcli/components.json"
tmp="/etc/auxcli/components.json.tmp"

jq '(.[] | select (.name == "raspiwifi") | .installed) = false' $config | sudo tee $tmp 1> /dev/null
sudo mv -f $tmp $config

sudo python3 /usr/lib/raspiwifi/uninstall.py
