#!/bin/bash
set -e


# If it finds UART, make sure it's off
sudo sed -i "s/^#enable_uart=1/enable_uart=0/g" /boot/config.txt
sudo sed -i "s/^#enable_uart=0/enable_uart=0/g" /boot/config.txt
sudo sed -i "s/^enable_uart=1/enable_uart=0/g" /boot/config.txt

if ! sudo grep "enable_uart=0" "/boot/config.txt"; then
    printf "\n# Disable UART\nenable_uart=0\n" | sudo tee -a /boot/config.txt
fi

config="/etc/auxcli/components.json"
tmp="/etc/auxcli/components.json.tmp"

jq '(.[] | select (.name == "uart") | .enabled) = false' $config | sudo tee $tmp
sudo mv -f $tmp $config