#!/bin/bash
set -e


# If it finds UART, make sure it's on
sudo sed -i "s/^#enable_uart=1/enable_uart=1/g" /boot/config.txt
sudo sed -i "s/^#enable_uart=0/enable_uart=1/g" /boot/config.txt
sudo sed -i "s/^enable_uart=0/enable_uart=1/g" /boot/config.txt

if ! sudo grep "enable_uart=1" "/boot/config.txt"; then
    printf "\n# Enable UART\nenable_uart=1\n" | sudo tee -a /boot/config.txt
fi

auxcli write "components" "uart" "enabled" "true"