#!/bin/bash
set -e

config_path=$(jq -r '.[] | select( .name == "dhcpcd" ) | .config_path' /etc/auxcli/commands.json)

args_short=($(jq -r '.[].arg_short' $config_path))
args_long=($(jq -r '.[].arg_long' $config_path))
args=("${args_short[@]}" "${args_long[@]}")

# readarray splits each newline into one element in the array
readarray -t args_desc < <(jq '.[].short_desc' $config_path)

usage() {
    printf "\nUsage:    auxcli dhcpcd [OPTIONS]\n\n"
    printf "Wrapper for setting and unsetting dhcpcd settings.\n\n"
    printf "OPTIONS:\n"
    for ((i = 0; i < ${#args[@]}; i++)); do
        printf "\t%-2s\t%-7s\t%s\n" "${arg_short[$i]}" "${args_long[$i]}" "${args_desc[$i]}"
    done
    exit 1
}

err_check() {
    # First error check
    # Show the usage menu if there aren't any arguments
    if [ $# -eq 0 ]; then
        printf "\nYou need to pass an argument.\n"
        usage
    fi

    # Second error check
    # Throw an error messege if the first argument isn't valid
    if [[ ! ${args[*]} =~ $1 ]]; then
        printf "\n\"$1\" is an invalid argument.\n"
        printf "Run auxcli dhcpcd -h for help.\n\n"
        exit 1
    fi
}

dhcpcd_set() {
    if auxcli hotspot -c; then
        if grep -q "static domain_name_servers=127.0.0.1 8.8.8.8 8.8.4.4" "/etc/dhcpcd.conf"; then
            echo "DHCPCD has already been set."
            return 0
        fi
        # if [ "$(cat /sys/class/net/eth0/operstate)" == "down" ]; then # TODO: Check for WiFi/Bluetooth Hotspot also.
        #     echo "You need a wired internet connection while in Hotspot/AP Mode to use the internet."
        #     return 1
        # fi
        echo "Modifying dchpcd.conf"
        echo "static domain_name_servers=127.0.0.1 8.8.8.8 8.8.4.4" | sudo tee -a /etc/dhcpcd.conf

        echo "Reloading dhcpcd"
        sudo systemctl daemon-reload
        sudo systemctl restart dhcpcd
        sleep 10
    else
        echo "There's no need to dhcpcd set."
        return 0
    fi
}

dhcpcd_unset() {
    if auxcli hotspot -c; then
        if grep -q "static domain_name_servers=127.0.0.1 8.8.8.8 8.8.4.4" "/etc/dhcpcd.conf"; then
            echo "Unmodifying dchpcd.conf"
            sudo sed -i '/^static domain_name_servers=127.0.0.1 8.8.8.8 8.8.4.4/d' /etc/dhcpcd.conf

            echo "Reloading dhcpcd"
            sudo systemctl daemon-reload
            sudo systemctl restart dhcpcd
            sleep 10
        else
            echo "DHCPCD wasn't set."
        fi
    fi
}

err_check "$@"

while [[ $# -gt 0 ]]; do
    case "$1" in

    -s | --set) #Set Hostname
        dhcpcd_set
        break # past argument
        ;;
    -u | --unset) #Set Hostname
        dhcpcd_unset
        break # past argument
        ;;
    -h | -help | --help)
        usage
        break # past argument
        ;;
    esac
done
