#!/bin/bash
set -e

sudo apt-get install -y \
    bluez-tools \
    python-dbus \
    python-gobject \
    python-gobject-2

old_dtimeout=$(grep DiscoverableTimeout /etc/bluetooth/main.conf)
new_dtimeout="DiscoverableTimeout = 0"
sudo sed -i "s/$old_dtimeout/$new_dtimeout/g" /etc/bluetooth/main.conf

old_ptimeout=$(grep PairableTimeout /etc/bluetooth/main.conf)
new_ptimeout="PairableTimeout = 0"
sudo sed -i "s/$old_ptimeout/$new_ptimeout/g" /etc/bluetooth/main.conf

auxcli-write "components" "tethering-ble" "installed" "true"