#!/bin/bash
set -e

if grep bullseye /etc/os-release; then
    sudo apt-get install -y \
        bluez-tools \
        python3-gi \
        python3-dbus
else
    sudo apt-get install -y \
        bluez-tools \
        python-dbus \
        python-gobject \
        python-gobject-2
fi

old_dtimeout=$(grep DiscoverableTimeout /etc/bluetooth/main.conf)
new_dtimeout="DiscoverableTimeout = 0"
sudo sed -i "s/$old_dtimeout/$new_dtimeout/g" /etc/bluetooth/main.conf

old_ptimeout=$(grep PairableTimeout /etc/bluetooth/main.conf)
new_ptimeout="PairableTimeout = 0"
sudo sed -i "s/$old_ptimeout/$new_ptimeout/g" /etc/bluetooth/main.conf

. $path_to_helper/write "components" "tethering-ble" "installed" "true"