#!/bin/bash
set -e

echo "Unmodifying dchpcd.conf"
sudo sed -i '/static domain_name_servers=8.8.8.8 8.8.4.4/d' /etc/dhcpcd.conf

echo "Reloading dhcpcd"
sudo systemctl daemon-reload
sudo systemctl restart dhcpcd
