#!/bin/bash
set -e

if pgrep -x "hostapd" >/dev/null 2>&1; then
    echo "You are in hotspot mode!"
    if [ "$(cat /sys/class/net/eth0/operstate)" == "down" ]; then
        echo "You need a wired internet connection while in Hotspot/AP Mode to use the internet."
        return 1
    fi
    return 0
else
    echo "You aren't in hotspot mode!"
    return 1
fi
