#!/bin/bash
set -e

usage() {
    printf "\nUsage:        auxcli disable [COMPONENT]\n\n"
    printf "Disable system related components of auxcli.\n\n"
    printf "COMPONENTS:\n"
    for ((i = 0; i < ${#components[@]}; i++)); do
        if . $path_to_helper/enabled ${components[$i]}; then
            printf "\t[x] %-24s\t%s\n" "${components[$i]}" "${components_desc[$i]}"
        elif ! . $path_to_helper/enabled ${components[$i]}; then
            printf "\t[ ] %-24s\t%s\n" "${components[$i]}" "${components_desc[$i]}"
        fi
    done
    printf "\t    %-2s\t%-14s\t%s\n" "-h" "--help" "Displays this usage information."
    exit 1
}

err_check() {
    # First error check
    # Show the usage menu if there aren't any arguments
    # or if the argument is "-h" or "--help"
    . $path_to_helper/debug-printf "DEBUG (disable): First error check.\n"
    if [ $# -eq 0 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        usage
    fi

    # Second error check
    # Throw an error messege if the first argument isn't a component
    . $path_to_helper/debug-printf "DEBUG (disable): Second error check.\n"
    if [[ ! ${components[*]} =~ $1 ]]; then
        printf "\n\"%s\" is not a valid component.\n" "$1"
        printf "Run 'auxcli disable -h' for help.\n\n"
        exit 1
    fi

    # Third error check
    # Throw an error messege if the component is already disabled
    . $path_to_helper/debug-printf "DEBUG (disable): Third error check.\n"
    if ! . $path_to_helper/enabled "$1"; then
        printf "\nThe \"%s\" component is already disabled.\n\n" "$1"
        exit 1
    fi
}

disable_component(){
    while [[ $# -gt 0 ]]; do
        . $path_to_helper/debug-printf "DEBUG (disable): Disabling component: %s\n" "$1"
        . /lib/auxcli/components/configuration/$1/disable
        shift
    done
}

err_check "$@"
disable_component "$@"
