#!/bin/bash
set -e

config_path=($(jq -r '.[] | select( .name == "hotspot" ) | .config_path' /etc/auxcli/commands.json))

args_short=($(jq -r '.[].arg_short' $config_path))
args_long=($(jq -r '.[].arg_long' $config_path))
args=("${args_short[@]}" "${args_long[@]}")

# readarray splits each newline into one element in the array
readarray -t args_desc < <(jq '.[].short_desc' $config_path)

usage() {
    printf "\nUsage:    auxcli hotspot [OPTIONS]\n\n"
    printf "Changes the hotspot mode your pi/axucli is in.\n\n"
    printf "OPTIONS:\n"
    for ((i = 0; i < ${#args[@]}; i++)); do
        printf "\t%-2s\t%-7s\t%s\n" "${arg_short[$i]}" "${args_long[$i]}" "${args_desc[$i]}"
    done
    exit 1
}

err_check() {
    # First error check
    # Show the usage menu if there aren't any arguments
    if [ $# -eq 0 ]; then
        printf "\nYou need to pass an argument.\n"
        usage
    fi

    # Second error check
    # Throw an error messege if the first argument isn't valid
    if [[ ! ${args[*]} =~ $1 ]]; then
        printf "\n\"$1\" is an invalid argument.\n"
        printf "Run auxcli hotspot -h for help.\n\n"
        exit 1
    fi
}

hotspot_check() {
    if pgrep -x "hostapd" >/dev/null 2>&1; then
        echo "You are in hotspot mode!"
        return 0
    else
        echo "You aren't in hotspot mode!"
        return 1
    fi
}

hotspot_enable() {
    sudo python3 /usr/lib/raspiwifi/reset_device/manual_reset.py
    echo "Hotspot Enabled!"
}

hotspot_disable() {
    # From app.py def set_ap_client_mode()
    sudo rm -f /etc/raspiwifi/host_mode || echo "/etc/raspiwifi/host_mode does not exist."
    sudo rm /etc/cron.raspiwifi/aphost_bootstrapper || echo "/etc/cron.raspiwifi/aphost_bootstrapper does not exist."
    sudo cp /usr/lib/raspiwifi/reset_device/static_files/apclient_bootstrapper /etc/cron.raspiwifi/
    sudo chmod +x /etc/cron.raspiwifi/apclient_bootstrapper
    sudo mv /etc/dnsmasq.conf.original /etc/dnsmasq.conf || sudo cp /lib/auxcli/modules/raspi-wifi/dnsmasq.conf /etc/dnsmasq.conf
    sudo mv /etc/dhcpcd.conf.original /etc/dhcpcd.conf || sudo cp /lib/auxcli/modules/raspi-wifi/dhcpcd.conf /etc/dhcpcd.conf
    sudo mv /etc/wpa_supplicant/wpa_supplicant.conf.original /etc/wpa_supplicant/wpa_supplicant.conf || echo "You're original wpa_supplicant.conf is missing."

    echo "Hotspot Disabled!"

    read -p "Disabling Hotspot Mode requires a reboot to take effect. Press 'y' to reboot now, or press anything else to exit." -n 1 -r
    echo # Gives us a newline
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        sudo reboot now
    else
        exit 1
    fi
}

err_check "$@"

while [[ $# -gt 0 ]]; do
    case "$1" in

    -c | --check) #Set Hostname
        hotspot_check
        break # past argument
        ;;
    -e | --enable) #Set Hostname
        hotspot_enable
        break # past argument
        ;;
    -d | --disable) #Set Hostname
        hotspot_disable
        break # past argument
        ;;
    -h | -help | --help)
        usage
        break # past argument
        ;;
    esac
done
