#!/bin/bash
set -e

# Disable Serial Console from tying up the process
sudo sed -i "s/console=serial0,115200 //g" /boot/cmdline.txt
sudo sed -i "s/console=ttyAMA0,115200 //g" /boot/cmdline.txt


config="/etc/auxcli/components.json"
tmp="/etc/auxcli/components.json.tmp"

jq '(.[] | select (.name == "serial-console") | .enabled) = false' $config | sudo tee $tmp 1> /dev/null
sudo mv -f $tmp $config