#!/bin/bash
set -e

auxcli debug-printf "DEBUG (serial-console-disable): Disabling serial-console.\n"

# Disable Serial Console from tying up the process
auxcli debug-printf "DEBUG (serial-console-disable): Removing serial0 from /boot/cmdline.txt\n"
sudo sed -i "s/console=serial0,115200 //g" /boot/cmdline.txt
auxcli debug-printf "DEBUG (serial-console-disable): Removing ttyAMA0 from /boot/cmdline.txt\n"
sudo sed -i "s/console=ttyAMA0,115200 //g" /boot/cmdline.txt

auxcli write "components" "serial-console" "enabled" "false"