#!/bin/bash
set -e

# Disable Serial Console from tying up the process
sudo sed -i "s/console=serial0,115200 //g" /boot/cmdline.txt
sudo sed -i "s/console=ttyAMA0,115200 //g" /boot/cmdline.txt

auxcli write "components" "serial-console" "enabled" "false"