#!/bin/bash
set -e

# Disable Serial Console from tying up the process
if ! sudo grep "console=serial0" "/boot/cmdline.txt"; then
    printf "console=serial0,115200" | sudo tee -a /boot/cmdline.txt
fi
if ! sudo grep "console=ttyAMA0" "/boot/cmdline.txt"; then
    printf "console=ttyAMA0,115200" | sudo tee -a /boot/cmdline.txt
fi

auxcli write "components" "serial-console" "enabled" "true"