#!/bin/bash
set -e

# Config path for uninstall
config_uninstall=$(jq -r '.[] | select( .name == "uninstall" ) | .config_path' $config_commands)
. $path_to_helper/debug-printf "DEBUG (uninstall): Config path: %s\n" "$config_uninstall"

# Arguments for uninstall
readarray -t args_short < <(jq -r '.[].arg_short' $config_uninstall)
readarray -t args_long < <(jq -r '.[].arg_long' $config_uninstall)
readarray -t args_desc < <(jq -r '.[].short_desc' $config_uninstall)
args=("${args_short[@]}" "${args_long[@]}")

usage() {
    printf "\nUsage:        auxcli uninstall [COMPONENT]\n\n"
    printf "Uninstall additional components of auxcli.\n\n"
    printf "COMPONENTS:\n"
    for ((i = 0; i < ${#components[@]}; i++)); do
        if . $path_to_helper/installed ${components[$i]}; then
            printf "\t[x] %-24s\t%s\n" "${components[$i]}" "${components_desc[$i]}"
        else
            printf "\t[ ] %-24s\t%s\n" "${components[$i]}" "${components_desc[$i]}"
        fi
    done
    printf "\t    %-10s\t\t\t%s\n" "everything" "Uninstall all tools."
    for ((i = 0; i < ${#args_desc[@]}; i++)); do
        printf "\t%-2s\t%-10s\t%s\n" "${arg_short[$i]}" "${args_long[$i]}" "${args_desc[$i]}"
    done
    exit 1
}

err_check() {
    # First error check
    # Show the usage menu if there aren't any arguments
    . $path_to_helper/debug-printf "DEBUG (uninstall): Error Check: 1 of 3\n"
    if [ $# -eq 0 ]; then
        usage
    fi

    # Second error check
    # Throw an error messege if the first argument isn't valid
    . $path_to_helper/debug-printf "DEBUG (uninstall): Error Check: 2 of 3\n"
    if [[ ! ${components[*]} =~ $1 ]] && [[ ! ${args[*]} =~ $1 ]]; then
        printf "\n\"%s\" is not a valid component or argument.\n" "$1"
        printf "Run 'auxcli uninstall -h' for help.\n\n"
        exit 1
    fi

    # Third error check
    # Throw an error messege if the component is already installed
    . $path_to_helper/debug-printf "DEBUG (uninstall): Error Check: 3 of 3\n"
    if ! . $path_to_helper/installed "$1"; then
        printf "\nThe \"%s\" component isn't installed.\n\n" "$1"
        exit 0
    fi
}

uninstall_component(){
    . $path_to_helper/debug-printf "DEBUG (uninstall): DHCPCD set check.\n"
    if . $path_to_helper/available dhcpcd; then auxcli dhcpcd -s; fi
    while [[ $# -gt 0 ]]; do
        if . $path_to_helper/requires-reboot "$1"; then
            . $path_to_helper/debug-printf "DEBUG (uninstall): %s requires a reboot.\n" "$1"
            . $path_to_helper/debug-printf "DEBUG (uninstall): Setting reboot_required to 'true'\n"
            . $path_to_helper/write "config" "reboot_required" "true"
        fi
        if [[ ${hardware[*]} =~ $1 ]]; then
            . $path_to_helper/debug-printf "DEBUG (uninstall): %s is a 'hardware' component.\n" "$1"
            . $path_to_helper/debug-printf "DEBUG (uninstall): Uninstalling: %s...\n" "$1"
            . /lib/auxcli/components/hardware/$1/uninstall
        fi
        if [[ ${tool[*]} =~ $1 ]]; then
            . $path_to_helper/debug-printf "DEBUG (uninstall): %s is a 'tool' component.\n" "$1"
            . $path_to_helper/debug-printf "DEBUG (uninstall): Uninstalling: %s...\n" "$1"
            . /lib/auxcli/components/tool/$1/uninstall
        fi
        shift
    done
    . $path_to_helper/debug-printf "DEBUG (uninstall): DHCPCD unset check.\n"
    if . $path_to_helper/available dhcpcd; then auxcli dhcpcd -u; fi
}

uninstall_everything(){
    . $path_to_helper/debug-printf "DEBUG (uninstall): Uninstalling everything...\n"
    uninstall_component "${tool[@]}"
}

err_check "$@"

while [[ $# -gt 0 ]]; do
    case "$1" in
    everything)
        uninstall_everything
        shift # past argument
        ;;
    -r | --reboot)
        . $path_to_helper/debug-printf "DEBUG (uninstall): Setting reboot_on_exit to 'true'\n"
        . $path_to_helper/write "config" "reboot_on_exit" "true"
        shift # past argument
        ;;
    -h | -help | --help)
        usage
        shift # past argument
        ;;
    *)
        uninstall_component "$1"
        shift # past argument
        ;;
    esac
done
