#!/bin/bash
set -e

sudo rm -rf /usr/bin/slack
sudo sed -i "/# Slack Start/,/# Slack End/d" /etc/rc.local

config="/etc/auxcli/components.json"
tmp="/etc/auxcli/components.json.tmp"
jq '(.[] | select (.name == "slack") | .installed) = false' $config | sudo tee $tmp 1> /dev/null
sudo mv -f $tmp $config
