#!/bin/bash
set -e

help_menu() {
    echo ""
    echo "Usage:    hotspot [OPTIONS]"
    echo ""
    echo "A tool that wraps the commands for allowing internet to passthrough a wired connection if available."
    echo ""
    echo "Options:"
    echo "-c    --check         Checks if you're in hotspot mode."
    echo "-e    --enable        Enables hotspot mode."
    echo "-d    --disable       Disables hotspot mode."
    echo "-h    --help          Displays this help information."
    echo ""
    exit 1
}

err_msg() {
    echo ""
    echo "\"$1\" is an invalid argument."
    echo "Run hotspot -h for help."
    echo ""
    exit 1
}

hotspot_check() {
    if pgrep -x "hostapd" >/dev/null 2>&1; then
        echo "You are in hotspot mode!"
        return 0
    else
        echo "You aren't in hotspot mode!"
        return 1
    fi
}

hotspot_enable() {
    sudo python3 /usr/lib/raspiwifi/reset_device/manual_reset.py
    echo "Hotspot Enabled!"
}

hotspot_disable() {
    # From app.py def set_ap_client_mode()
    sudo rm -f /etc/raspiwifi/host_mode || echo "/etc/raspiwifi/host_mode does not exist."
    sudo rm /etc/cron.raspiwifi/aphost_bootstrapper || echo "/etc/cron.raspiwifi/aphost_bootstrapper does not exist."
    sudo cp /usr/lib/raspiwifi/reset_device/static_files/apclient_bootstrapper /etc/cron.raspiwifi/
    sudo chmod +x /etc/cron.raspiwifi/apclient_bootstrapper
    sudo mv /etc/dnsmasq.conf.original /etc/dnsmasq.conf || sudo cp /lib/aux-cli/modules/raspi-wifi/dnsmasq.conf /etc/dnsmasq.conf
    sudo mv /etc/dhcpcd.conf.original /etc/dhcpcd.conf || sudo cp /lib/aux-cli/modules/raspi-wifi/dhcpcd.conf /etc/dhcpcd.conf

    echo "Hotspot Disabled!"

    read -p "Disabling Hotspot Mode requires a reboot to take effect. Press 'y' to reboot now, or press anything else to exit." -n 1 -r
    echo # Gives us a newline
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        sudo reboot now
    else
        exit 1
    fi
}

if [ $# -eq 0 ]; then
    echo ""
    echo "You need to pass an argument."
    help_menu
fi

while [[ $# -gt 0 ]]; do
    case "$1" in

    -c | --check) #Set Hostname
        hotspot_check
        break # past argument
        ;;
    -e | --enable) #Set Hostname
        hotspot_enable
        break # past argument
        ;;
    -d | --disable) #Set Hostname
        hotspot_disable
        break # past argument
        ;;
    -h | -help | --help)
        help_menu
        break # past argument
        ;;
    *) # any option
        err_msg "$1"
        shift # past argument
        ;;
    esac
done
