#!/bin/bash
set -e

error_msg="Docker Compose failed to start."
echo "Starting Docker."
if [ -e /data/db/mongod.lock ]; then
    sudo rm -rf /data/db/mongod.lock
fi

# If hotspot mode is enabled, bypass it temporarily
aux-cli dhcpcd -s

while [[ $(docker-compose up -d || echo "$error_msg") == "$error_msg" ]]; do
    echo "Docker isn't started yet."
    sleep 1
done

aux-cli dhcpcd -u

echo "Docker is started."
