#!/bin/bash
set -e

docker stop $(docker ps -a -q)



# AUX_DOCKER_IMAGES=( "pi_server_1" "pi_nginx_1" "pi_redis_1" "pi_mongo_1" )

# for image in "${AUX_DOCKER_IMAGES[@]}"; do
#     docker stop $(docker ps -f name="${image}" -q)
#     echo "${image}"
# done
