#!/bin/bash
set -e

help_menu() {
    echo ""
    echo "Usage:    update [OPTIONS]"
    echo ""
    echo "A tool that wraps the commands for updating AUX and software installed via apt-get."
    echo ""
    echo "Options:"
    echo "-a    --aux           Updates AUX to the latest version."
    echo "-c    --cli           Updates CLI to the latest version."
    echo "-p    --pi            Alias for apt-get update/upgrade"
    echo "-h    --help          Displays this help information."
    echo ""
    exit 1
}

err_msg() {
    echo ""
    echo "\"$1\" is an invalid argument."
    echo "Run update -h for help."
    echo ""
    exit 1
}

update_aux() {
    # If hotspot mode is true, then do the work around
    if aux-cli hotspot -c; then
        aux-cli dhcpcd -s
        sleep 10
        docker-compose pull && docker-compose up -d
        sleep 10
        aux-cli dhcpcd -u
    # Else, run as normal
    else
        docker-compose pull && docker-compose up -d
    fi
}

update_cli() {
    # If hotspot mode is true, then do the work around
    if aux-cli hotspot -c; then
        aux-cli dhcpcd -s
        sleep 10
        curl https://raw.githubusercontent.com/casual-simulation/aux-cli/master/install.sh --output install.sh && sudo bash install.sh
        sudo rm -rf install.sh
        sleep 10
        aux-cli dhcpcd -u
    # Else, run as normal
    else
        curl https://raw.githubusercontent.com/casual-simulation/aux-cli/master/install.sh --output install.sh && sudo bash install.sh
        sudo rm -rf install.sh
    fi
}

update_pi() {
    # If hotspot mode is true, then do the work around
    if aux-cli hotspot -c; then
        aux-cli dhcpcd -s
        sleep 10
        sudo apt-get update && apt-get upgrade -y
        sleep 10
        aux-cli dhcpcd -u
    # Else, run as normal
    else
        sudo apt-get update && apt-get upgrade -y
    fi
}

if [ $# -eq 0 ]; then
    echo ""
    echo "You need to specify what to update."
    help_menu
fi

while [[ $# -gt 0 ]]; do
    case "$1" in

    -a | --aux) #Set Hostname
        update_aux
        shift # past argument
        ;;
    -c | --cli) #Set Hostname
        update_cli
        shift # past argument
        ;;
    -p | --pi) #Set Hostname
        update_pi
        shift # past argument
        ;;
    -h | -help | --help)
        help_menu
        shift # past argument
        ;;
    *) # any option
        err_msg "$1"
        shift # past argument
        ;;
    esac
done
