#!/bin/bash
set -e

echo "Starting reboot operations."

dnsmasq_conf="/etc/dnsmasq.conf"
hostapd_conf="/etc/hostapd/hostapd.conf"
dhcpcd_conf="/etc/dhcpcd.conf"
wpa_conf="/etc/wpa_supplicant/wpa_supplicant.conf"

read_conf() {
    . /etc/aux-cli.conf
}

wlan_checker() {
    # Check if there is an extra wlan present and use it
    if grep wlan1 /proc/net/dev; then
        sudo sed -i "s/interface=wlan0/interface=wlan1/g" "${dnsmasq_conf}"
        sudo sed -i "s/interface=wlan0/interface=wlan1/g" "${hostapd_conf}"
        sudo sed -i "s/interface wlan0/interface wlan1/g" "${dhcpcd_conf}"
    fi
}

dnsmasq_checker() {
    if [ -e "${dnsmasq_conf}" ]; then
        # Give a larger default range of IP Addresses with a longer timeout
        if sudo grep "dhcp-range=" "${dnsmasq_conf}"; then
            sudo sed -i "s/dhcp-range=.*/dhcp-range=10.0.0.10,10.0.0.110,12h/g" "${dnsmasq_conf}"
        else
            echo "dhcp-range=10.0.0.10,10.0.0.110,12h" | sudo tee -a "${dnsmasq_conf}"
        fi

        # Add the auxplayer name
        if ! sudo grep "address=/auxplayer.com/10.0.0.1" "${dnsmasq_conf}"; then
            echo "address=/auxplayer.com/10.0.0.1" | sudo tee -a "${dnsmasq_conf}"
        fi
    fi
}

wpa_checker() {
    if [ -e "${wpa_conf}" ]; then
        if sudo grep "country=" "${wpa_conf}"; then
            sudo sed -i "s/country=.*/country=US/g" "${wpa_conf}"
        else
            line_number=$(sudo grep -ne '^$' "${wpa_conf}" | grep -Eo '^[^:]+')
            sudo sed -i "${line_number}i country=US" "${wpa_conf}"
        fi

        if sudo grep "scan_ssid=" "${wpa_conf}"; then
            sudo sed -i "s/scan_ssid=.*/scan_ssid=1/g" "${wpa_conf}"
        else
            line_number=$(sudo grep -n "network=" "${wpa_conf}" | grep -Eo '^[^:]+')
            line_number=$((line_number + 1))
            sudo sed -i "${line_number}i \\ \\ \\ \\ scan_ssid=1" "${wpa_conf}"
        fi
    fi
}

mac_check() {
    echo "Checking the MAC."
    oldfour=$(grep -Eo "ssid=.*? ...." /etc/hostapd/hostapd.conf | tail -c 5)
    newfour=$(tail -c 6 /sys/class/net/eth0/address | tr --delete :)
}

mac_set() {
    if [ "$oldfour" != "$newfour" ]; then
        sudo sed -i "s/$oldfour/$newfour/g" /etc/hostapd/hostapd.conf
        reboot_required="true"
        echo "MAC has been updated."
    else
        echo "MAC Address matches."
    fi
}

hostname_check() {
    echo "Checking the hostname"
    oldhost=$(grep -Eo "ssid=.*" /etc/hostapd/hostapd.conf | sed 's/.\{5\}$//' | sed "s/ssid=//g")
    oldhost2=$(grep -Eo "ssid_prefix=.*" /etc/raspiwifi/raspiwifi.conf | sed "s/ssid_prefix=//g")
}

hostname_set() {
    if [ "$(hostname)" != "$oldhost" ]; then
        sudo sed -i "s/$oldhost/$(hostname)/g" /etc/hostapd/hostapd.conf
        reboot_required="true"
    else
        echo "OldHost matches NewHost."
    fi
    if [ "$(hostname)" != "$oldhost2" ]; then
        sudo sed -i "s/$oldhost2/$(hostname)/g" /etc/raspiwifi/raspiwifi.conf
        reboot_required="true"
    else
        echo "OldHost2 matches NewHost."
    fi
}

reboot_check() {
    if [ "$reboot_required" == "true" ]; then
        sudo reboot now
    fi
}

run_steps() {
    reboot_required="false"
    read_conf
    wlan_checker
    dnsmasq_checker
    wpa_checker
    if [ $raspiwifi == "true" ]; then
        mac_check
        mac_set
        hostname_check
        hostname_set
    fi
    if [ $first_run == "true" ]; then
        aux-cli start
        sudo sed -i "s/first_run=\"true\"/first_run=\"false\"/g" /etc/aux-cli.conf
    fi
    reboot_check
}

run_steps
