#!/bin/bash
set -e

docker_check() {
    echo "Starting Docker."

    error_msg="Docker Compose failed to start."
    while [[ $(docker-compose up -d || echo "$error_msg") == "$error_msg" ]]; do
        echo "Docker isn't started yet."
        sleep 1
    done

    echo "Docker is started."

}

usbmount_docker_check() {
    currentMounts=$(sudo mount | grep "/dev/sd[a-z][0-9]" | grep -vE "docker" | grep -vE "(/|/boot) " | awk '{print $1,$3}')
    for i in "${!currentMounts[@]}"; do
        if [[ "${currentMounts[i]}" == *[!\ ]* ]]; then
            echo "Unmounting USB Device: ${currentMounts[i]}"
            sudo umount $(echo "${currentMounts[i]}" | awk '{print $2}' | xargs echo -n)
            echo "Mounting USB Device: ${currentMounts[i]}"
            sudo mount $(echo "${currentMounts[i]}" | awk '{print $1,$2}')
        fi
    done
}

run_steps() {
    docker_check
    
    if auxcli installed "usbmount"; then
        usbmount_docker_check
    fi

}

run_steps