#!/bin/bash
set -e

if [[ $(jq --arg component "$1" -r '.[] | select( .name == $component ) | .requires_reboot' /etc/auxcli/components.json) == "true" ]]; then
    auxcli-debug-printf "DEBUG (requires-reboot): %s requires reboot.\n" "$1"
    return 0
else
    auxcli-debug-printf "DEBUG (requires-reboot): %s does not require reboot.\n" "$1"
    return 1
fi
