#!/bin/bash
set -e

if [[ $(jq --arg component "$1" -r '.[] | select( .name == $component ) | .enabled' /etc/auxcli/components.json) == "true" ]]; then
    auxcli-debug-printf "DEBUG (enabled): %s is enabled.\n" "$1"
    return 0
else
    auxcli-debug-printf "DEBUG (enabled): %s is not enabled.\n" "$1"
    return 1
fi
