#!/bin/bash
set -e

if [[ $(jq --arg command "$1" '.[] | select( .name == $command ) | .available' /etc/auxcli/commands.json) == "true" ]]; then
    # echo "$1 is available."
    exit 0
else
    # echo "$1 is not available."
    exit 1
fi
