#!/bin/bash
set -e

if $(jq --arg command "$1" -r '.[] | select( .name == $command ) | .available' /etc/auxcli/commands.json); then
    . $path_to_helper/debug-printf "DEBUG (available): %s is available.\n" "$1"
    return 0
else
    . $path_to_helper/debug-printf "DEBUG (available): %s is not available.\n" "$1"
    return 1
fi
