#!/bin/bash
set -e

if $(jq --arg command "$1" -r '.[] | select( .name == $command ) | .available' /etc/auxcli/commands.json); then
    . /lib/auxcli/commands/helper/debug-printf "DEBUG (available): %s is available.\n" "$1"
    exit 0
else
    . /lib/auxcli/commands/helper/debug-printf "DEBUG (available): %s is not available.\n" "$1"
    exit 1
fi
