#!/bin/bash
set -e

# sudo rfcomm connect /dev/rfcomm0 AA:BB:CC:DD:EE 1 &
# sudo rfcomm connect $device $mac $channel &
sudo rfcomm connect "$1" "$2" "$3" &

while ! (sudo rfcomm -a | grep "$2"); do 
    sleep 1
    echo "Not Connected Yet."
done