#!/bin/bash

config_devices="/etc/auxcli/devices.json"
path_to_helper="/lib/auxcli/commands/helper"
readarray -t current_devices < <(jq -r '.[].mac' $config_devices)

scan_devices(){
    readarray -t discovered_devices < <(hcitool scan)
    for ((i = 1; i < ${#discovered_devices[@]}; i++)); do
        device_mac=$(echo ${discovered_devices[i]} | awk '{print $1}')
        device_name=$(echo ${discovered_devices[i]} | awk '{print $2}')
        . $path_to_helper/write "devices" $device_mac $device_name $device_desc
    done
}

first_scan(){
    while [ ${#current_devices[@]} -eq 0 ]; do
        scan_devices
        readarray -t current_devices < <(jq -r '.[].mac' $config_devices)
    done
}

first_scan
scan_devices
