#!/bin/bash
set -e

# sudo rfcomm release /dev/rfcomm0
# sudo rfcomm release $device
sudo rfcomm release "$1"

# readarray -t processes < <(pgrep -f "/dev/rfcomm0")
readarray -t processes < <(pgrep -f "$1")

for ((i = 0; i < ${#processes[@]}; i++)); do
    sudo kill -9 "${processes[$i]}"
done
