#!/bin/bash
set -e

devices_config="/etc/auxcli/devices.json"

# Get array of device names
# Maybe give them a "custom ID" from casualOS to pass to this command?
# Check if any of those are "on"
#

sudo rfcomm release "$1"

sudo killall rfcomm
