#!/bin/bash
set -e

config_devices="/etc/auxcli/devices.json"
path_to_helper="/lib/auxcli/commands/helper"
readarray -t current_devices < <(jq -r '.[].mac' $config_devices)

# sudo rfcomm connect /dev/rfcomm0 AA:BB:CC:DD:EE
sudo rfcomm connect "$1" $device01_mac 1 &

while ! (sudo rfcomm -a | grep $device01_mac); do 
    sleep 1
    echo "Not Connected Yet."
done