#!/bin/bash
set -e

if $(jq --arg component "$1" -r '.[] | select( .name == $component ) | .enabled' /etc/auxcli/components.json); then
    . $path_to_helper/debug-printf "DEBUG (enabled): %s is enabled.\n" "$1"
    return 0
else
    . $path_to_helper/debug-printf "DEBUG (enabled): %s is not enabled.\n" "$1"
    return 1
fi
