#!/bin/bash
set -e

if [[ $(jq --arg component "$1" '.[] | select( .name == $component ) | .enabled' /etc/auxcli/components.json) == "true" ]]; then
    # echo "$1 is enabled."
    exit 0
else
    # echo "$1 is not enabled."
    exit 1
fi
