#!/bin/bash
set -e

path_to_helper="/lib/auxcli/commands/helper"

# Config paths
config_main="/etc/auxcli/config.json"
config_main_tmp="/etc/auxcli/config.json.tmp"
config_commands="/etc/auxcli/commands.json"
config_commands_tmp="/etc/auxcli/commands.json.tmp"
config_components="/etc/auxcli/components.json"
config_components_tmp="/etc/auxcli/components.json.tmp"
config_devices="/etc/auxcli/devices.json"
config_devices_tmp="/etc/auxcli/devices.json.tmp"

if [ -f /etc/auxcli/config.json ]; then
    first_boot=$(jq -r '.first_boot' /etc/auxcli/config.json) 
else
    first_boot=true
fi

if [[ $first_boot == "true" ]]; then
    printf "DEBUG (first-boot): Pulling docker-compose images.\n"
    docker-compose -f /home/pi/docker-compose.yml pull 

    printf "DEBUG (first-boot): Starting docker-compose images.\n"
    docker-compose -f /home/pi/docker-compose.yml up -d

    . $path_to_helper/write "config" "first_boot" "false"
fi