#!/bin/bash
set -e

path_to_helper="/lib/auxcli/commands/helper"

hostapd_conf="/etc/hostapd/hostapd.conf"
raspiwifi_conf="/etc/raspiwifi/raspiwifi.conf"
host=$(hostname)

mac_check() {
    printf "DEBUG (hotspot-checker): Checking the MAC...\n"

    oldfour=$(grep -Eo "ssid=.*? ...." $hostapd_conf | tail -c 5)
    printf "DEBUG (hotspot-checker): The last 4 characters of the old MAC are: %s\n" "$oldfour"

    newfour=$(tail -c 6 /sys/class/net/eth0/address | tr --delete :)
    printf "DEBUG (hotspot-checker): The last 4 characters of the new MAC are: %s\n" "$newfour"
}

mac_set() {
    if [ "$oldfour" != "$newfour" ]; then
        printf "DEBUG (hotspot-checker): The MAC is different...\n"

        printf "DEBUG (hotspot-checker): Updating the MAC...\n"
        sudo sed -i "s/$oldfour/$newfour/g" $hostapd_conf

        printf "DEBUG (hotspot-checker): Setting reboot_required to 'true'\n"
        . $path_to_helper/write "config" "reboot_required" "true"

        printf "DEBUG (hotspot-checker): Setting reboot_on_exit to 'true'\n"
        . $path_to_helper/write "config" "reboot_on_exit" "true"

        printf "DEBUG (hotspot-checker): MAC has been updated.\n"
    else
        printf "DEBUG (hotspot-checker): MAC Address matches.\n"
    fi
}

hostname_check() {
    printf "DEBUG (hotspot-checker): Checking the hostname...\n"

    oldhost=$(grep -Eo "ssid=.*" $hostapd_conf | sed 's/.\{5\}$//' | sed "s/^ssid=//g")
    printf "DEBUG (hotspot-checker): The hostapd old hostname is: %s\n" "$oldhost"

    oldhost2=$(grep -Eo "ssid_prefix=.*" $raspiwifi_conf | sed "s/^ssid_prefix=//g")
    printf "DEBUG (hotspot-checker): The raspiwifi old hostname is: %s\n" "$oldhost2"
}

hostname_set() {
    if [ "$host" != "$oldhost" ]; then
        printf "DEBUG (hotspot-checker): hostapd hostname has changed.\n"

        printf "DEBUG (hotspot-checker): Updating the hostapd hostname.\n"
        sudo sed -i "s/$oldhost/$host/g" $hostapd_conf

        printf "DEBUG (hotspot-checker): Setting reboot_required to 'true'\n"
        . $path_to_helper/write "config" "reboot_required" "true"

        printf "DEBUG (hotspot-checker): Setting reboot_on_exit to 'true'\n"
        . $path_to_helper/write "config" "reboot_on_exit" "true"

    else
        printf "DEBUG (hotspot-checker): hostapd hostname has not changed.\n"
    fi
    if [ "$host" != "$oldhost2" ]; then
        printf "DEBUG (hotspot-checker): raspiwifi hostname has changed.\n"

        printf "DEBUG (hotspot-checker): Updating the raspiwifi hostname.\n"
        sudo sed -i "s/$oldhost2/$host/g" $raspiwifi_conf

        printf "DEBUG (hotspot-checker): Setting reboot_required to 'true'\n"
        . $path_to_helper/write "config" "reboot_required" "true"

        printf "DEBUG (hotspot-checker): Setting reboot_on_exit to 'true'\n"
        . $path_to_helper/write "config" "reboot_on_exit" "true"

    else
        printf "DEBUG (hotspot-checker): raspiwifi hostname has not changed.\n"
    fi
}

if . $path_to_helper/installed "raspiwifi"; then
    mac_check
    mac_set
    hostname_check
    hostname_set
fi