#!/bin/bash
set -e

config="/etc/auxcli/components.json"

if [[ $(jq --arg component "$1" '.[] | select( .name == $component ) | .installed' $config) == "true" ]]; then
    # echo "$1 is installed."
    exit 0
else
    # echo "$1 is not installed."
    exit 1
fi
