#!/bin/bash
set -e

if [[ $(jq --arg component "$1" -r '.[] | select( .name == $component ) | .installed' /etc/auxcli/components.json) == "true" ]]; then
    . $path_to_helper/debug-printf "DEBUG (installed): %s is installed.\n" "$1"
    return 0
else
    . $path_to_helper/debug-printf "DEBUG (installed): %s is not installed.\n" "$1"
    return 1
fi
