#!/bin/bash
set -e

if $(jq --arg component "$1" -r '.[] | select( .name == $component ) | .installed' /etc/auxcli/components.json); then
    # echo "$1 is installed."
    exit 0
else
    # echo "$1 is not installed."
    exit 1
fi
