#!/bin/bash
set -e

path_to_helper="/lib/auxcli/commands/helper"

# Config paths
config_main="/etc/auxcli/config.json"
config_main_tmp="/etc/auxcli/config.json.tmp"
config_commands="/etc/auxcli/commands.json"
config_commands_tmp="/etc/auxcli/commands.json.tmp"
config_components="/etc/auxcli/components.json"
config_components_tmp="/etc/auxcli/components.json.tmp"
config_devices="/etc/auxcli/devices.json"
config_devices_tmp="/etc/auxcli/devices.json.tmp"

. $path_to_helper/debug-printf "DEBUG (reboot-reset): Resetting reboot_on_exit to false.\n"
. $path_to_helper/write "config" "reboot_on_exit" "false"

. $path_to_helper/debug-printf "DEBUG (reboot-reset): Resetting reboot_required to false.\n"
. $path_to_helper/write "config" "reboot_required" "false"
