#!/bin/bash
set -e

if $(jq --arg component "$1" -r '.[] | select( .name == $component ) | .requires_reboot' /etc/auxcli/components.json 1> /dev/null); then
    auxcli debug-printf "DEBUG (requires-reboot): %s requires reboot.\n" "$1"
    exit 0
else
    auxcli debug-printf "DEBUG (requires-reboot): %s does not require reboot.\n" "$1"
    exit 1
fi
