#!/bin/bash
set -e

if $(jq --arg component "$1" -r '.[] | select( .name == $component ) | .requires_reboot' /etc/auxcli/components.json); then
    # echo "$1 requires reboot."
    exit 0
else
    # echo "$1 does not require reboot."
    exit 1
fi
