#!/bin/bash

read_conf() {
    . /etc/aux-cli.conf
}

usbmount_docker_check() {
    echo "Waiting to usbmount to docker..."
    if ! docker inspect -f '{{.State.Running}}' pi_server_1; then
        echo "Docker is not up yet..."
        sleep 2
    else
        echo "Docker is up!"
        currentMounts=$(sudo mount | grep "/dev/sd[a-z][0-9]" | grep -vE "docker" | grep -vE "(/|/boot) " | awk '{print $1,$3}')
        for i in "${!currentMounts[@]}"; do
            if [[ "${currentMounts[i]}" == *[!\ ]* ]]; then
                echo "Unmounting USB Device: ${currentMounts[i]}"
                sudo umount $(echo "${currentMounts[i]}" | awk '{print $2}' | xargs echo -n)
                echo "Mounting USB Device: ${currentMounts[i]}"
                sudo mount $(echo "${currentMounts[i]}" | awk '{print $1,$2}')
            fi
        done
    fi
}


run_steps() {
    read_conf

    if [ $usbmount == "true" ]; then
        usbmount_docker_check
    fi

}