#!/bin/bash
set -e

# Change directory to the folder this file is in
cd "$(dirname "${BASH_SOURCE}")"

# TODO: Grab a list of all install scripts next to this file, maybe make a manifest or something?

# for filename in $(find /lib/aux-cli/modules -type f ! -name "*.*" ! -name install ! -name install ! -name reinstall ! -name uninstall); do
#     basename "${filename}"
# done

help_menu() {
    echo ""
    echo "Usage:    install [OPTIONS]"
    echo ""
    echo "A tool to install modules/pods/packages for your pi."
    echo ""
    echo "Options:"
    echo "pishrink          Installs a tool for shrinking pi images."
    echo "raspiwifi         Installs a tool to enable/disable hotspot mode."
    echo "rfid              Installs a collection of tools to work with RFID a reader/writer."
    echo "zerotier          Installs a tool to do stuff."
    echo "tethering         Installs a collection of tools to allow tethering via usb or bluetooth."
    echo "usbmount          Installs a tool for automatically mounting external storage to a specified directory."
    echo "nfchat            Installs a collection of tools to work with NFC a reader/writer"
    echo "slack             Installs a tool to message Slack from the command line."
    echo "almosteverything  Installs everything available except for RaspiWiFi."
    echo "everything        Installs everything available."
    echo ""
    exit 1
}

err_msg() {
    echo ""
    echo "\"$1\" is an invalid argument."
    echo "Run install -h for help."
    echo ""
    exit 1
}

if [ $# -eq 0 ]; then
    echo ""
    echo "You need to specify what to install."
    help_menu
fi

while [[ $# -gt 0 ]]; do
    case "$1" in

    pishrink)
        aux-cli dhcpcd -s
        . pishrink
        shift # past argument
        ;;
    raspiwifi)
        aux-cli dhcpcd -s
        . raspiwifi
        shift # past argument
        ;;
    rfid)
        aux-cli dhcpcd -s
        . rfid
        shift # past argument
        ;;
    zerotier)
        aux-cli dhcpcd -s
        . zerotier
        shift # past argument
        ;;
    tethering)
        aux-cli dhcpcd -s
        . tethering
        shift # past argument
        ;;
    usbmount)
        aux-cli dhcpcd -s
        . usbmount
        shift # past argument
        ;;
    nfchat)
        aux-cli dhcpcd -s
        . nfchat
        shift # past argument
        ;;
    slack)
        aux-cli dhcpcd -s
        . slack
        shift # past argument
        ;;
    almosteverything)
        aux-cli dhcpcd -s
        . pishrink
        . rfid
        . zerotier
        . usbmount
        . nfchat
        . slack
        . tethering
        shift # past argument
        ;;
    everything)
        aux-cli dhcpcd -s
        . pishrink
        . rfid
        . zerotier
        . usbmount
        . nfchat
        . slack
        . tethering
        . raspiwifi
        shift # past argument
        ;;
    -h | -help | --help)
        help_menu
        shift # past argument
        ;;
    *) # any option
        err_msg "$1"
        shift # past argument
        ;;
    esac
done

aux-cli dhcpcd -u
