#!/bin/bash
set -e

install() {
    if ! [ -e /usr/local/bin/pishrink.sh ]; then
        echo "Installing PiShrink now."
        wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
        sudo chmod +x pishrink.sh
        sudo mv -f pishrink.sh /usr/local/bin
    else
        echo "PiShrink is already installed."
    fi
}

uninstall() {
    echo "stuff"
}

if [ "$1" == "uninstall" ]; then
    uninstall
else
    install
fi
