#!/bin/bash
set -e

install() {
    if ! [ -e /usr/local/bin/pishrink.sh ]; then
        echo "Installing PiShrink."
        sudo wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
        sudo chmod +x pishrink.sh
        sudo mv -f pishrink.sh /usr/local/bin
    else
        echo "PiShrink is already installed."
    fi
    sudo sed -i "s/pishrink=\"false\"/pishrink=\"true\"/g" /etc/aux-cli.conf
}

uninstall() {
    echo "Uninstalling Pishrink."
    sudo rm -rf /usr/local/bin/pishrink.sh
    sudo sed -i "s/pishrink=\"true\"/pishrink=\"false\"/g" /etc/aux-cli.conf
}

if [ "$1" == "uninstall" ]; then
    uninstall
else
    install
fi
