#!/bin/bash
set -e

working_dir="$( cd "$(dirname "$0")" ; pwd -P )"

# Change directory to the folder this file is in
cd "${working_dir}"

sudo apt-get install -y git

# Clone RaspiWiFi
echo "DEBUG: Cloning RaspiWiFi..."
if [ ! -d RaspiWiFi ]; then
    git clone https://github.com/jasbur/RaspiWiFi.git
fi

# Add in our custom scripts to bypass interactivity
echo "DEBUG: Modifying RaspiWiFi..."
cp "${working_dir}/raspi-wifi/initial_setup.py" RaspiWiFi
cp "${working_dir}/raspi-wifi/config.json" RaspiWiFi
cp "${working_dir}/raspi-wifi/reset_lib.py" RaspiWiFi/libs/reset_device

# Run the RaspiWiFi setup
echo "DEBUG: Running RaspiWiFi..."
cd RaspiWiFi
sudo python3 initial_setup.py

# Clear out the repo afterwards
sudo rm -rf RaspiWiFi
