#!/bin/bash
set -e

install() {
    working_dir=$(
        cd $(dirname "${BASH_SOURCE}")
        pwd -P
    )

    # Change directory to the folder this file is in
    cd "${working_dir}"

    sudo apt-get install -y git

    # Clone RaspiWiFi
    if [ ! -d "${working_dir}/RaspiWiFi" ]; then
        echo "DEBUG: Cloning RaspiWiFi..."
        sudo mkdir "${working_dir}/RaspiWiFi"
        sudo git clone https://github.com/jasbur/RaspiWiFi.git
    fi

    # Add in our custom scripts to bypass interactivity
    echo "DEBUG: Modifying RaspiWiFi..."
    sudo cp "${working_dir}/raspi-wifi/initial_setup.py" RaspiWiFi
    sudo cp "${working_dir}/raspi-wifi/config.json" RaspiWiFi
    sudo cp "${working_dir}/raspi-wifi/reset_lib.py" RaspiWiFi/libs/reset_device

    # Run the RaspiWiFi setup
    echo "DEBUG: Running RaspiWiFi..."
    sudo sed -i "s/raspiwifi=\"false\"/raspiwifi=\"true\"/g" /etc/aux-cli.conf
    cd RaspiWiFi
    sudo python3 initial_setup.py # Triggers a reboot

    # Clear out the repo afterwards - Never makes it here
    sudo rm -rf "${working_dir}/RaspiWiFi"
}

uninstall() {
    sudo apt autoremove
    if [ -e /usr/lib/raspiwifi/uninstall.py ]; then
        sudo sed -i "s/raspiwifi=\"true\"/raspiwifi=\"false\"/g" /etc/aux-cli.conf
        sudo python3 /usr/lib/raspiwifi/uninstall.py
    fi
    sudo apt autoremove
}

if [ "$1" == "uninstall" ]; then
    uninstall
else
    install
fi
