#!/bin/bash
set -e

# Change directory to the folder this file is in
cd "$(dirname "${BASH_SOURCE}")"

# TODO: Grab a list of all install scripts next to this file, maybe make a manifest or something?

help_menu() {
    echo ""
    echo "Usage:    reinstall [OPTIONS]"
    echo ""
    echo "A tool to reinstall modules/pods/packages for your pi."
    echo ""
    echo "Options:"
    echo "pishrink      Reinstalls a tool for shrinking pi images."
    echo "raspiwifi     Reinstalls a tool to enable/disable hotspot mode."
    echo "rfid          Reinstalls a collection of tools to work with RFID a reader/writer."
    echo "zerotier      Reinstalls a tool to do stuff."
    echo "usbmount      Reinstalls a tool for automatically mounting external storage to a specified directory."
    echo "nfchat        Reinstalls a collection of tools to work with NFC a reader/writer"
    echo "slack         Reinstalls a tool to message Slack from the command line."
    echo "tethering     Reinstalls a collection of tools to allow tethering via usb or bluetooth."
    echo "everything    Reinstalls everything available"
    echo ""
    exit 1
}


err_msg() {
    echo ""
    echo "\"$1\" is an invalid argument."
    echo "Run reinstall -h for help."
    echo ""
    exit 1
}

if [ $# -eq 0 ]; then
    echo ""
    echo "You need to specify what to reinstall."
    help_menu
fi

while [[ $# -gt 0 ]]; do
    case "$1" in

    pishrink)
        aux-cli uninstall pishrink
        aux-cli install pishrink
        shift # past argument
        ;;
    raspiwifi)
        aux-cli uninstall raspiwifi
        aux-cli install raspiwifi
        shift # past argument
        ;;
    rfid)
        aux-cli uninstall rfid
        aux-cli install rfid
        shift # past argument
        ;;
    zerotier)
        aux-cli uninstall zerotier
        aux-cli install zerotier
        shift # past argument
        ;;
    usbmount)
        aux-cli uninstall usbmount
        aux-cli install usbmount
        shift # past argument
        ;;
    nfchat)
        aux-cli uninstall nfchat
        aux-cli install nfchat
        shift # past argument
        ;;
    slack)
        aux-cli uninstall slack
        aux-cli install slack
        shift # past argument
        ;;
    tethering)
        aux-cli uninstall tethering
        aux-cli install tethering
        shift # past argument
        ;;
    everything)
        aux-cli uninstall pishrink
        aux-cli install pishrink

        aux-cli uninstall raspiwifi
        aux-cli install raspiwifi

        aux-cli uninstall rfid
        aux-cli install rfid

        aux-cli uninstall zerotier
        aux-cli install zerotier

        aux-cli uninstall usbmount
        aux-cli install usbmount

        aux-cli uninstall nfchat
        aux-cli install nfchat

        aux-cli uninstall slack
        aux-cli install slack

        aux-cli uninstall tethering
        aux-cli install tethering
        shift # past argument
        ;;
    -h | -help | --help)
        help_menu
        shift # past argument
        ;;
    *) # any option
        err_msg "$1"
        shift # past argument
        ;;
    esac
done
