#!/bin/bash
set -e

read_conf() {
    . /etc/aux-cli.conf
}

install() {
    sudo cp slack_msg/slack /usr/bin/slack
    sudo chmod +x /usr/bin/slack

    sudo sed -i '/^exit 0/d' /etc/rc.local

    sudo tee -a "/etc/rc.local" > /dev/null <<EOT
if [ -e /boot/slack ]; then

    slack_default_webhook=\$(sed -n '1p' /boot/slack)
    if [ ! -z "\$slack_default_webhook" ]; then
        sudo sed -i '/^APP_SLACK_WEBHOOK=/d' /etc/environment
        echo "APP_SLACK_WEBHOOK=\$slack_default_webhook" | sudo tee -a /etc/environment
    fi

    slack_default_channel=\$(sed -n '2p' /boot/slack)
    if [ ! -z "\$slack_default_channel" ]; then
        sudo sed -i '/^APP_SLACK_CHANNEL=/d' /etc/environment
        echo "APP_SLACK_CHANNEL=\$slack_default_channel" | sudo tee -a /etc/environment
    fi

    slack_default_username=\$(sed -n '3p' /boot/slack)
    if [ ! -z "\$slack_default_username" ]; then
        sudo sed -i '/^APP_SLACK_USERNAME=/d' /etc/environment
        echo "APP_SLACK_USERNAME=\$slack_default_username" | sudo tee -a /etc/environment
    fi

    slack_default_icon=\$(sed -n '4p' /boot/slack)
    if [ ! -z "\$slack_default_icon" ]; then
        sudo sed -i '/^APP_SLACK_ICON_EMOJI=/d' /etc/environment
        echo "APP_SLACK_ICON_EMOJI=\$slack_default_icon" | sudo tee -a /etc/environment
    fi

    rm /boot/slack
fi

exit 0
EOT

    sudo sed -i "s/^slack=\"false\"/slack=\"true\"/g" /etc/aux-cli.conf
}

uninstall() {
    sudo rm -rf /usr/bin/slack
    
    sudo sed -i "s/^slack=\"true\"/slack=\"false\"/g" /etc/aux-cli.conf
}

read_conf

if [ "$1" == "uninstall" ]; then
    if [ $slack == "true" ]; then
        uninstall
    else
        echo "Slack is not installed. Skipping uninstallation."
    fi
else
    if [ $slack == "false" ]; then
        install
    else
        echo "Slack is already installed. Skipping installation."
    fi
fi
