#!/bin/bash
set -e

usb_tethering() {
    # Connect via usb and trust after this runs
    sudo apt-get install -y usbmuxd
    sudo systemctl enable usbmuxd
    sudo systemctl start usbmuxd
}

ble_tethering() {

    sudo apt-get install bluez-tools -y

    sudo cp -rf /lib/aux-cli/modules/ble/pan0.netdev /etc/systemd/network
    sudo cp -rf /lib/aux-cli/modules/ble/pan0.network /etc/systemd/network
    sudo cp -rf /lib/aux-cli/modules/ble/bt-agent.service /etc/systemd/system
    sudo cp -rf /lib/aux-cli/modules/ble/bt-network.service /etc/systemd/system

    sudo systemctl enable systemd-networkd
    sudo systemctl enable bt-agent
    sudo systemctl enable bt-network
    sudo systemctl start systemd-networkd
    sudo systemctl start bt-agent
    sudo systemctl start bt-network

    sudo bt-adapter --set PairableTimeout 0
    sudo bt-adapter --set Pairable 1
    sudo bt-adapter --set DiscoverableTimeout 0
    sudo bt-adapter --set Discoverable 1

}

install() {
    usb_tethering
    ble_tethering
    sudo sed -i "s/tethering=\"false\"/tethering=\"true\"/g" /etc/aux-cli.conf
}

uninstall() {
    sudo apt autoremove
    sudo apt-get remove -y usbmuxd
    sudo apt-get remove -y bluez-tools
    sudo apt autoremove
    
    sudo rm -rf /etc/systemd/network/pan0.netdev
    sudo rm -rf /etc/systemd/network/pan0.network
    sudo rm -rf /etc/systemd/system/bt-agent.service
    sudo rm -rf /etc/systemd/system/bt-network.service
    sudo systemctl disable systemd-networkd
    sudo systemctl stop systemd-networkd
    sudo sed -i "s/tethering=\"true\"/tethering=\"false\"/g" /etc/aux-cli.conf
}

if [ "$1" == "uninstall" ]; then
    uninstall
else
    install
fi
