#!/bin/bash
set -e

install() {
    # Install Zero Tier
    echo "DEBUG: Installing ZeroTier..."
    curl -s https://install.zerotier.com/ | sudo bash

    # Join Zero Tier Network
    #sudo zerotier-cli join $zt_network && sudo zerotier-cli info
}

uninstall() {
    sudo apt-get remove zerotier-one
}

if [ "$1" == "uninstall" ]; then
    uninstall
else
    install
fi
