#!/bin/bash
set -e

# Connect via usb and trust after this runs
sudo apt-get install -y usbmuxd
sudo systemctl enable usbmuxd
sudo systemctl start usbmuxd

config="/etc/auxcli/components.json"
tmp="/etc/auxcli/components.json.tmp"
jq '(.[] | select (.name == "tethering-usb") | .installed) = true' $config | sudo tee $tmp 1> /dev/null
sudo mv -f $tmp $config