#!/bin/bash
set -e

# Connect via usb and trust after this runs
sudo apt-get install -y usbmuxd
sudo systemctl enable usbmuxd
sudo systemctl start usbmuxd

auxcli write "components" "tethering-usb" "installed" "true"